# Generated by Django 3.1.7 on 2021-05-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba_3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laba3result',
            name='G',
            field=models.ImageField(upload_to='images/laba_3'),
        ),
        migrations.AlterField(
            model_name='laba3result',
            name='img_after',
            field=models.ImageField(upload_to='images/laba_3'),
        ),
    ]
